version: '3.8'

services:
  db:
    image: mariadb
    container_name: callcenter-db
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./db/mysqldata/conf.d:/etc/mysql/conf.d
      - ./db/mysqldata/initdb.d:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
      - MYSQL_MAX_CONNECTIONS=1000
      - MYSQL_CONNECT_TIMEOUT=60
      - MYSQL_WAIT_TIMEOUT=28800
      - MYSQL_INTERACTIVE_TIMEOUT=28800
    command:
      - --max_connections=1000
      - --connect_timeout=60
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=128M
      - --innodb_buffer_pool_size=1G
      - --innodb_log_file_size=256M
      - --innodb_flush_log_at_trx_commit=2
      - --innodb_flush_method=O_DIRECT
    networks:
      - app-network

  data-migration:
    build: ./data-migration
    volumes:
      - ./data-migration/init-data:/app/init-data
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    depends_on:
      - db
    networks:
      - app-network

  data-sync:
    build: ./data-schedule-sync
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    depends_on:
      - data-migration
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: 