version: '3.8'

services:
  callcenter-db:
    image: mariadb:11.7.2
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
      - MYSQL_MAX_CONNECTIONS=1000
      - MYSQL_CONNECT_TIMEOUT=60
      - MYSQL_WAIT_TIMEOUT=28800
      - MYSQL_INTERACTIVE_TIMEOUT=28800
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000
      - --connect_timeout=60
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=128M
      - --innodb_buffer_pool_size=1G
      - --innodb_log_file_size=256M
      - --innodb_flush_log_at_trx_commit=2
      - --innodb_flush_method=O_DIRECT
    ports:
      - "33306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data-migration/init-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  data-migration:
    build: ./data-migration
    environment:
      - NODE_ENV=production
      - DB_HOST=callcenter-db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    volumes:
      - ./data-migration/init-data:/app/init-data
    depends_on:
      - callcenter-db
    networks:
      - app-network

  data-schedule-sync:
    build: ./data-schedule-sync
    environment:
      - NODE_ENV=production
      - DB_HOST=callcenter-db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    depends_on:
      - callcenter-db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge