version: '3.8'

services:
  data-schedule-sync:
    build: .
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal
      - DB_PORT=33306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    command: ["node", "dist/index.js"]
    init: true
    container_name: data-schedule-sync
    rm: true

networks:
  app-network:
    driver: bridge